-- MySQL Script generated by MySQL Workbench
-- Thu Nov 21 12:59:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tesis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tesis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tesis` ;
USE `tesis` ;

-- -----------------------------------------------------
-- Table `tesis`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis`.`carrera` (
  `Id_carrera` INT NOT NULL,
  `Nom_carrera` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id_carrera`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tesis`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis`.`autor` (
  `boleta` INT NOT NULL,
  `nombre` VARCHAR(40) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `apellidos` VARCHAR(40) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `correo` VARCHAR(70) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `telefono` INT NOT NULL,
  `Id_carrera` INT NULL DEFAULT NULL,
  `RutaImagen` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`boleta`),
  INDEX `Id_carrera` (`Id_carrera` ASC) VISIBLE,
  CONSTRAINT `autor_ibfk_1`
    FOREIGN KEY (`Id_carrera`)
    REFERENCES `tesis`.`carrera` (`Id_carrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesis`.`documentot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis`.`documentot` (
  `Id_Tesis` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Resumen` VARCHAR(500) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Fecha_Publicacion` VARCHAR(11) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Palabras_Clave` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Archivo` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Id_Carrera` INT NULL DEFAULT NULL,
  `Asesor` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Tesis`),
  INDEX `Id_Carrera` (`Id_Carrera` ASC) VISIBLE,
  CONSTRAINT `documentot_ibfk_1`
    FOREIGN KEY (`Id_Carrera`)
    REFERENCES `tesis`.`carrera` (`Id_carrera`))
ENGINE = InnoDB
AUTO_INCREMENT = 5;


-- -----------------------------------------------------
-- Table `tesis`.`tesis_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis`.`tesis_autor` (
  `Id_Tesis` INT NOT NULL,
  `boleta` INT NOT NULL,
  PRIMARY KEY (`Id_Tesis`, `boleta`),
  INDEX `boleta` (`boleta` ASC) VISIBLE,
  CONSTRAINT `tesis_autor_ibfk_1`
    FOREIGN KEY (`Id_Tesis`)
    REFERENCES `tesis`.`documentot` (`Id_Tesis`),
  CONSTRAINT `tesis_autor_ibfk_2`
    FOREIGN KEY (`boleta`)
    REFERENCES `tesis`.`autor` (`boleta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tesis`.`tesis_palabrasclave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis`.`tesis_palabrasclave` (
  `Id_Tesis` INT NOT NULL,
  `PalabraClave` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id_Tesis`, `PalabraClave`),
  CONSTRAINT `tesis_palabrasclave_ibfk_1`
    FOREIGN KEY (`Id_Tesis`)
    REFERENCES `tesis`.`documentot` (`Id_Tesis`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tesis`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_nombre` VARCHAR(40) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish2_ci' NOT NULL,
  `usuario_apellido` VARCHAR(40) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish2_ci' NOT NULL,
  `usuario_usuario` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish2_ci' NOT NULL,
  `usuario_clave` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish2_ci' NOT NULL,
  `usuario_email` VARCHAR(70) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish2_ci' NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
